name: Build and push container image

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - name: Login to registry
        uses: docker/login-action@v2
        with:
          registry: "ghcr.io/jonaskop"
          username: "${{ github.actor }}"
          password: "${{ github.token }}"

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "ghcr.io/jonaskop/argocd-external-secrets-sidecar:latest"
